<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="YCSPC009" name="com.qa.test.CountryTest" tests="2" failures="0" timestamp="22 Oct 2020 02:54:46 GMT" time="43.207" errors="1">
  <testcase name="loginTest" time="43.207" classname="com.qa.test.CountryTest"/>
  <testcase name="getUserTest" time="0.000" classname="com.qa.test.CountryTest">
    <error type="java.lang.Throwable" message="Method CountryTest.getUserTest()[pri:0, instance:com.qa.test.CountryTest@4520ebad] depends on not successfully finished methods in group &quot;user_post&quot;">
      <![CDATA[java.lang.Throwable: Method CountryTest.getUserTest()[pri:0, instance:com.qa.test.CountryTest@4520ebad] depends on not successfully finished methods in group "user_post"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </error>
  </testcase> <!-- getUserTest -->
</testsuite> <!-- com.qa.test.CountryTest -->
